#!/usr/bin/env bash
# ============================================================================
#  OpenPBX — one-shot droplet bootstrap for DigitalOcean
#  Target droplet public IP: 178.128.155.236
# ----------------------------------------------------------------------------
#  Run as root on a fresh Ubuntu 22.04/24.04 droplet, from the repo root:
#       sudo bash pbx/deploy/bootstrap-droplet.sh
#
#  It will:
#    1. install Docker + compose plugin (if missing)
#    2. generate pbx/.env with strong random secrets (idempotent: kept if present)
#    3. open the UFW firewall for SIP / RTP / T.38 / web
#    4. build and start the whole stack
#    5. print the admin login + next steps
#
#  Override any default by exporting the var before running, e.g.:
#       PUBLIC_HOSTNAME=pbx.mycompany.com sudo -E bash pbx/deploy/bootstrap-droplet.sh
# ============================================================================
set -euo pipefail

# ---- settings (override via environment) -----------------------------------
PUBLIC_IP="${PUBLIC_IP:-178.128.155.236}"
# Use the IP as the hostname until a real DNS name + TLS cert are in place.
PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-$PUBLIC_IP}"
BOOTSTRAP_ADMIN_EMAIL="${BOOTSTRAP_ADMIN_EMAIL:-admin@example.com}"

# Resolve repo paths relative to this script (pbx/deploy/bootstrap-droplet.sh).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PBX_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PBX_DIR/.env"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root (sudo)." >&2; exit 1
fi

# ---- 1. Docker -------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker…"
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  log "Installing docker compose plugin…"
  apt-get update -y && apt-get install -y docker-compose-plugin
fi

# ---- 2. .env with generated secrets ---------------------------------------
rand() { openssl rand -hex "${1:-24}"; }

if [[ -f "$ENV_FILE" ]]; then
  log ".env already exists — keeping it (delete it to regenerate)."
else
  log "Generating $ENV_FILE with strong secrets…"
  ADMIN_PW="$(rand 12)"
  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap-droplet.sh on $(date -u +%FT%TZ)
PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME
PUBLIC_IP=$PUBLIC_IP
LOCAL_NET=172.20.0.0/16

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=openpbx
POSTGRES_USER=openpbx
POSTGRES_PASSWORD=$(rand 24)

ARI_USERNAME=openpbx-ari
ARI_PASSWORD=$(rand 24)
AMI_USERNAME=openpbx-ami
AMI_PASSWORD=$(rand 24)

JWT_SECRET=$(rand 32)
BOOTSTRAP_ADMIN_EMAIL=$BOOTSTRAP_ADMIN_EMAIL
BOOTSTRAP_ADMIN_PASSWORD=$ADMIN_PW
ACCESS_TOKEN_TTL_MINUTES=720

RTP_START=10000
RTP_END=10200
SIP_UDP_PORT=5060
SIP_TCP_PORT=5060
SIP_TLS_PORT=5061
WSS_PORT=8089

TLS_CERT_FILE=/etc/asterisk/keys/fullchain.pem
TLS_KEY_FILE=/etc/asterisk/keys/privkey.pem

PUBLIC_BASE_URL=https://$PUBLIC_HOSTNAME
PROVISION_BASE_URL=https://$PUBLIC_HOSTNAME

RETENTION_ENABLED=true
RETENTION_INTERVAL_HOURS=24
CALL_JOURNAL_ENABLED=true
CALL_JOURNAL_INTERVAL_SECONDS=30
NOTIFICATIONS_ENABLED=true
NOTIFY_POLL_SECONDS=15
NOTIFY_MAX_ATTEMPTS=5
NOTIFY_DIGEST_THRESHOLD=3
BILLING_AUTOFINALIZE_ENABLED=true
BILLING_RUN_DAY=1
BILLING_CHECK_HOURS=6

# Optional integrations — fill in later, then: docker compose up -d
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=true
SMTP_FROM=OpenPBX <noreply@$PUBLIC_HOSTNAME>
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_SMS_FROM=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
FLOW_STASIS_APP=openpbx-flow
TRANSCRIPTION_PROVIDER=
TTS_PROVIDER=
OPENAI_API_KEY=
OPENAI_TRANSCRIBE_MODEL=whisper-1
OPENAI_TTS_MODEL=gpt-4o-mini-tts
OPENAI_TTS_VOICE=alloy
EOF
  chmod 600 "$ENV_FILE"
  echo "$ADMIN_PW" > "$PBX_DIR/deploy/ADMIN_PASSWORD.txt"
  chmod 600 "$PBX_DIR/deploy/ADMIN_PASSWORD.txt"
fi

# ---- 3. Firewall (UFW) -----------------------------------------------------
if command -v ufw >/dev/null 2>&1; then
  log "Configuring UFW firewall…"
  ufw allow 22/tcp                 >/dev/null   # keep SSH open!
  ufw allow 80,443/tcp             >/dev/null   # console + API
  ufw allow 5060/tcp               >/dev/null   # SIP TCP
  ufw allow 5061/tcp               >/dev/null   # SIP TLS
  ufw allow 8089/tcp               >/dev/null   # WebRTC WSS
  ufw allow 5060/udp               >/dev/null   # SIP UDP
  ufw allow 10000:10200/udp        >/dev/null   # RTP media
  ufw allow 4000:4999/udp          >/dev/null   # T.38 fax (UDPTL)
  ufw --force enable               >/dev/null
  echo "UFW rules applied (SSH 22 left open)."
else
  echo "ufw not present; ensure these are open at the DO cloud firewall:"
  echo "  TCP 22,80,443,5060,5061,8089   UDP 5060,10000-10200,4000-4999"
fi

# ---- 4. Build + start ------------------------------------------------------
log "Building and starting the stack (first run compiles images)…"
cd "$PBX_DIR"
docker compose up -d --build

log "Waiting for the API to become healthy…"
for i in $(seq 1 60); do
  if curl -fsk "https://localhost/api/health" >/dev/null 2>&1 \
     || curl -fs  "http://localhost/api/health" >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

# ---- 5. Summary ------------------------------------------------------------
log "Done. OpenPBX is starting on this droplet."
cat <<EOF

  Console:     https://$PUBLIC_HOSTNAME/
  API health:  https://$PUBLIC_HOSTNAME/api/health
  Admin email: $BOOTSTRAP_ADMIN_EMAIL
  Admin pass:  $( [[ -f "$PBX_DIR/deploy/ADMIN_PASSWORD.txt" ]] && cat "$PBX_DIR/deploy/ADMIN_PASSWORD.txt" || echo "(see your .env BOOTSTRAP_ADMIN_PASSWORD)" )

  NOTE: TLS is self-signed until you point a real domain at $PUBLIC_IP and
        install a Let's Encrypt cert (see pbx/docs/DEPLOYMENT.md §4). Browsers
        will warn about the cert; that's expected on first boot.

  Check status:   docker compose ps
  Tail logs:      docker compose logs -f asterisk api
EOF
