"""Extensions (SIP phones / WebRTC softphones) within a tenant."""
from __future__ import annotations

import secrets

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from .. import db
from ..asterisk import dialplan_reload, pjsip_reload
from ..deps import tenant_slug
from ..dialplan_gen import regenerate_tenant
from ..provisioning import deprovision_extension, provision_extension

router = APIRouter(prefix="/api/tenants/{tenant_id}/extensions", tags=["extensions"])


class ExtensionIn(BaseModel):
    extension: str
    display_name: str
    email: str | None = None
    sip_password: str | None = None        # autogenerated if omitted
    webrtc: bool = True
    voicemail_enabled: bool = True
    vm_pin: str = "0000"
    outbound_cid: str | None = None
    ring_seconds: int = 25


class ExtensionPatch(BaseModel):
    display_name: str | None = None
    email: str | None = None
    sip_password: str | None = None
    call_forward: str | None = None
    dnd: bool | None = None
    voicemail_enabled: bool | None = None
    vm_pin: str | None = None
    outbound_cid: str | None = None
    ring_seconds: int | None = None


@router.get("")
async def list_extensions(ts: tuple[int, str] = Depends(tenant_slug)) -> list[dict]:
    tid, _ = ts
    rows = await db.fetch(
        """SELECT e.*, (c.id IS NOT NULL) AS registered
           FROM extensions e
           LEFT JOIN ps_contacts c ON c.endpoint = e.endpoint_id
           WHERE e.tenant_id = $1 ORDER BY e.extension""",
        tid,
    )
    return [dict(r) for r in rows]


@router.post("", status_code=201)
async def create_extension(body: ExtensionIn,
                           ts: tuple[int, str] = Depends(tenant_slug)) -> dict:
    tid, slug = ts

    # Enforce the tenant's plan extension cap.
    cap = await db.fetchval(
        """SELECT p.max_extensions FROM tenants t JOIN plans p ON p.id = t.plan_id
           WHERE t.id = $1""", tid)
    used = await db.fetchval("SELECT count(*) FROM extensions WHERE tenant_id = $1", tid)
    if cap is not None and used >= cap:
        raise HTTPException(402, f"Plan limit reached ({cap} extensions). Upgrade plan.")

    dup = await db.fetchval(
        "SELECT 1 FROM extensions WHERE tenant_id=$1 AND extension=$2",
        tid, body.extension)
    if dup:
        raise HTTPException(409, "extension already exists")

    sip_password = body.sip_password or secrets.token_urlsafe(18)
    async with db.tx() as con:
        async with con.transaction():
            endpoint_id = await provision_extension(
                con, tenant_id=tid, slug=slug, extension=body.extension,
                display_name=body.display_name, sip_password=sip_password,
                webrtc=body.webrtc, ring_seconds=body.ring_seconds,
            )
            await con.execute(
                """INSERT INTO extensions
                     (tenant_id, extension, display_name, endpoint_id, email,
                      outbound_cid, voicemail_enabled, vm_pin, ring_seconds, webrtc)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)""",
                tid, body.extension, body.display_name, endpoint_id, body.email,
                body.outbound_cid, body.voicemail_enabled, body.vm_pin,
                body.ring_seconds, body.webrtc,
            )
            if body.voicemail_enabled:
                await con.execute(
                    """INSERT INTO voicemail (context, mailbox, password, fullname, email, tenant_id)
                       VALUES ($1,$2,$3,$4,$5,$6)
                       ON CONFLICT (context, mailbox) DO UPDATE SET password = EXCLUDED.password""",
                    slug, body.extension, body.vm_pin, body.display_name, body.email, tid,
                )
    # Refresh this tenant's BLF hint context so the new extension is monitorable.
    await regenerate_tenant(slug)
    await dialplan_reload()
    return {"extension": body.extension, "endpoint_id": endpoint_id,
            "sip_username": endpoint_id, "sip_password": sip_password,
            "wss_uri": f"wss://{slug}/ws"}


@router.patch("/{extension}")
async def update_extension(extension: str, body: ExtensionPatch,
                           ts: tuple[int, str] = Depends(tenant_slug)) -> dict:
    tid, slug = ts
    row = await db.fetchrow(
        "SELECT * FROM extensions WHERE tenant_id=$1 AND extension=$2", tid, extension)
    if not row:
        raise HTTPException(404, "extension not found")

    sets, vals = [], []
    for f in ("display_name", "email", "call_forward", "dnd",
              "voicemail_enabled", "vm_pin", "outbound_cid", "ring_seconds"):
        v = getattr(body, f)
        if v is not None:
            vals.append(v)
            sets.append(f"{f} = ${len(vals)}")
    if sets:
        vals += [tid, extension]
        await db.execute(
            f"UPDATE extensions SET {', '.join(sets)} "
            f"WHERE tenant_id = ${len(vals)-1} AND extension = ${len(vals)}",
            *vals,
        )
    if body.sip_password:
        await db.execute(
            "UPDATE ps_auths SET password=$1 WHERE id=$2",
            body.sip_password, row["endpoint_id"])
    if body.vm_pin is not None:
        await db.execute(
            "UPDATE voicemail SET password=$1 WHERE context=$2 AND mailbox=$3",
            body.vm_pin, slug, extension)
    await pjsip_reload()
    return dict(await db.fetchrow(
        "SELECT * FROM extensions WHERE tenant_id=$1 AND extension=$2", tid, extension))


@router.delete("/{extension}", status_code=204)
async def delete_extension(extension: str,
                           ts: tuple[int, str] = Depends(tenant_slug)):
    tid, slug = ts
    row = await db.fetchrow(
        "SELECT endpoint_id FROM extensions WHERE tenant_id=$1 AND extension=$2",
        tid, extension)
    if not row:
        raise HTTPException(404, "extension not found")
    async with db.tx() as con:
        async with con.transaction():
            await deprovision_extension(con, row["endpoint_id"])
            await con.execute(
                "DELETE FROM extensions WHERE tenant_id=$1 AND extension=$2", tid, extension)
            await con.execute(
                "DELETE FROM voicemail WHERE context=$1 AND mailbox=$2", slug, extension)
            # drop any BLF keys this extension owned
            await con.execute(
                "DELETE FROM blf_keys WHERE tenant_id=$1 AND extension=$2", tid, extension)
    await regenerate_tenant(slug)
    await pjsip_reload()
    await dialplan_reload()
